# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables: 
  imageName: eshop/payment.api

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    Dockerfile: src/Services/Payment/Payment.API/Dockerfile
    repository: $(imageName)
    buildContext: src
    command: build
    