apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rabbit
  labels: 
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: test-rabbit
        image: bisio/test-rabbit:0.6
        env:
        - name: RABBIT_HOST
          value: rabbitmq

